name: nota
description: "Unlock the power of organized thoughts with Nota, the sleek and intuitive note-taking app designed for simplicity and efficiency. Whether you're jotting down quick ideas, drafting detailed notes, or organizing your to-do lists, Nota is your go-to app for capturing and managing your thoughts seamlessly."

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.6
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4
  cloud_firestore: ^5.2.1
  dio: ^5.6.0
  flutter_staggered_grid_view: ^0.7.0
  uuid: ^4.4.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    # Uncomment and specify asset paths if needed
    - assets/images/
    # - images/a_dot_ham.jpeg

  fonts:
    - family: Sofia
      fonts:
        - asset: assets/fonts/Sofia-Pro_Bold.otf
          weight: 700
        - asset: assets/fonts/Sofia-Pro_Medium.otf
          weight: 500
        - asset: assets/fonts/Sofia-Pro_Regular.otf
          weight: 400
